### ISSUE TITLE
Keep getting "Session error: You should be in clj(s) session"

### ISSUE THREAD

**Issue by Fedreg** [liquidz/vim-iced#137]
Hi, recently set up a new machine and started getting this error: 

<img width="364" alt="image" src="https://user-images.githubusercontent.com/17401067/63207413-fc27d700-c08a-11e9-9f9b-f37640015371.png">

It happens on both clj and cljs sessions.  With clj sometimes I see that error but then can continue using the repl with no issues.  With cljs, can never get past this error.

Looks like my `current_session_key` is not getting set correctly but not sure what is causing that. Any ideas?  Emacs is still my daily driver; could I have some dependency conflict in nrepl?   

Iced Repl starts fine
Master branch

Thanks for any help!

**Comment by liquidz** [comment]
@Fedreg Thank you for your reporting!
I could not reproduce the problem with NVIM v0.3.8 and vim-iced master branch.
I tested following steps.

* Start REPL with GraalJS
  * https://liquidz.github.io/vim-iced/vim-iced.html#vim-iced-graaljs
* Open `*.clj` file and execute `:IcedConnect` to connect nREPL
  * `clj` session
    * Evaluate some codes.
* Open `*.cljs` file and execute `:IcedStartCljsRepl graaljs` to switch to `cljs` session
  * `cljs` session
    * Evaluate some codes.
* Open `*.clj` file again. Session is switched to `clj` automatically.
  * `clj` session
    * Evaluate some codes.
* Open `*.cljs` file again. Session is switched to `cljs` automatically.
  * `cljs` session
    * Evaluate some codes.

Which nvim version are you using?
Could you tell me steps to reproduce the problem?

**Comment by Fedreg** [comment]
Thanks for the quick reply!

mvim 0.4.0-dev
<img width="635" alt="image" src="https://user-images.githubusercontent.com/17401067/63212946-c1489200-c0d0-11e9-9c67-47dd60d774ee.png">
 Let me create a minimal project that I can reproduce on and I'll send it to you.  Thx!

**Comment by Fedreg** [comment]
To reproduce.   
1. `$ lein new iced-test`
2. `$ iced repl`
3. Open `*.clj` file
4. `:IcedConnect` -> ..connects fine
5.  eval any expression -> "Session error. You should be in cli session.

Same thing if I do a cljs project

Cider 21.0, cider/nrepl 21.1 if that helps.    

Can you tell me what `current_session_key` is looking for to connect?

thx!

**Comment by liquidz** [comment]
@Fedreg 
> nvim 0.4.0-dev

Oh, it may relate to #134 
I'm working on `dev` branch, so could you try `dev` branch?

> To reproduce.

Thanks!
In my environment, `:IcedConnect` failed like #134 , and I could reproduce `Session error. You should be in clj session.` error.

> Can you tell me what current_session_key is looking for to connect?

`current_session_key` must be `'clj'` or `'cljs'` . ([c.f. 1](https://github.com/liquidz/vim-iced/blob/0.11.0/autoload/iced/nrepl.vim#L76-L82))
And initial `current_session_key` is `'clj'` basically. ([c.f. 2](https://github.com/liquidz/vim-iced/blob/0.11.0/autoload/iced/nrepl.vim#L377))
But if error is occured while connecting nREPL, `current_session_key` may be empty because `current_session_key` is changed after nREPL connected. ([c.f. 3](https://github.com/liquidz/vim-iced/blob/0.11.0/autoload/iced/nrepl.vim#L325))
In this case, vim-iced will validate empty `current_session_key` and the editing file extension, and throw above error. ([c.f. 4](https://github.com/liquidz/vim-iced/blob/0.11.0/autoload/iced/nrepl.vim#L100-L113))

Does this make sense?

**Comment by Fedreg** [comment]
Thanks!!

I pulled in dev and error is gone on clojure, so thank you for the quick fix!!

Still getting the error on cljs but I'll take a look at the notes you added and see if I can do anything.

In the meantime, If this is related to nvim 0.4.0 I can revert to 3.8 until that's resolve, no big deal.

I'll go ahead and close this issue but if I can send any more info to help, let me know.

Thx again!

**Comment by liquidz** [comment]
@Fedreg Currently vim-iced and cljs works well for me in nvim 0.4.0.
If you have any problems with latest vim-iced yet, please open a new issue :)
