### ISSUE TITLE
Validate dependencies and middlewares in shadow-cljs.edn

### ISSUE THREAD

**Issue by liquidz** [liquidz/vim-iced#140]
Branched by https://github.com/liquidz/vim-iced/issues/135#issuecomment-523682874

**Comment by liquidz** [comment]
@knubie I added shadow-cljs.edn validation on starting cljs repl via #143 !

**Comment by frankitox** [comment]
Just something to keep in mind but you can have false positives of this warning if you use shadow-cljs with other tool. For example, if you use `deps.edn` to specify the [dependencies](https://liquidz.github.io/vim-iced/vim-iced.html#vim-iced-manual-shadow-cljs). Because the code only searches for the deps in `shadow-cljs.edn`.

**Comment by liquidz** [comment]
@frankitox It's good to know. Thanks a lot!

Could you create a new issue?

**Comment by frankitox** [comment]
Yes, sure. I'll create an issue with more details.
