### ISSUE TITLE
auto-completion and signature do not show up !?

### ISSUE THREAD

**Issue by FongHou** [liquidz/vim-iced#146]
Does vim-iced support auto-completion out of the box (ie, what's showed here https://twitter.com/uochan/status/1154792252167741440)? I don't see auto-completion mentioned in the manual at all.

btw, I use nvim-v0.4 with coc.nvim installed, but no clojure feature enabled there.

Thanks!

**Comment by liquidz** [comment]
@FongHou vim-iced does not provide functionality for auto-completion. Only omni-completion is provided.

But you're lucky!
I created a source for coc.nvim recently.
https://github.com/liquidz/vim-iced-coc-source
With this plugin, you can get auto-completion functionality.

> btw, I use nvim-v0.4 with coc.nvim installed, but no clojure feature enabled there.
Did you connect to nrepl?
If not, please follow this steps.
https://liquidz.github.io/vim-iced/vim-iced.html#vim-iced-nrepl-connection

Otherwise could you tell me minimal steps to reproduce?

**Comment by FongHou** [comment]
Hi @liquidz, it works great. Thanks a lot for the quick response!
