### ISSUE TITLE
Add RenameSymbol command

### ISSUE THREAD

**Issue by nbardiuk** [liquidz/vim-iced#261]
A new command that prompts the user for a new name and replaces all occurrences of the symbol in the project.

Example from documentation in emacs https://github.com/clojure-emacs/clj-refactor.el/wiki/cljr-rename-symbol

**Comment by nbardiuk** [comment]
I am willing to contribute the feature to the project.

Could you please give me some direction on where the functionality should be implemented?
My initial thought is to start hacking in iced-nrepl but there is also refactor-nrepl.

**Comment by liquidz** [comment]
@nbardiuk I'm glad to hear that!
It may be a bit difficult to implement for the first contribution.
But you will understand vim-iced better when you implemented this feature.

First of all, I think it's better to have basically the same implementation as clj-refactor.el (because that's the feature we want).
https://github.com/clojure-emacs/clj-refactor.el/blob/v2.5.0/clj-refactor.el#L2650

1. refactor.el use the [find-symbol](https://github.com/clojure-emacs/refactor-nrepl#find-symbol) op provided by refactor-nrepl, so we need a function to call this op.
   * Functions for refactor-nrepl are defined under [autoload/iced/nrepl/op/refactor.vim](https://github.com/liquidz/vim-iced/blob/master/autoload/iced/nrepl/op/refactor.vim).
   * But there are two caveats with the `find-symbol` op
     * The response from refactor-nrepl will be returned in multiple parts, and you will need to process them together
       * c.f. https://github.com/liquidz/vim-iced/blob/2.2.0/autoload/iced/nrepl/op/cider.vim#L267
     * The response from refactor-nrepl is in EDN format and there is no function to easily parse it
       * There is a way to decode by [jet](https://github.com/borkdude/jet)
         * https://github.com/liquidz/vim-iced/blob/2.2.0/autoload/iced/nrepl/test/plain.vim#L18-L24
1. Add the rename-symbol function to this file.
   * It's good to add it to this [autoload/iced/nrepl/refactor.vim](https://github.com/liquidz/vim-iced/blob/2.2.0/autoload/iced/nrepl/refactor.vim)
   * This function will call find-symbol op, parse the response and rewrite buffers.
     * The renaming process is a vim buffer operation, so it may be hard work...
1. Add command, `<Plug>` mapping, and default mapping
   * e.g.
     * https://github.com/liquidz/vim-iced/blob/2.2.0/ftplugin/clojure.vim#L155
     * https://github.com/liquidz/vim-iced/blob/2.2.0/ftplugin/clojure.vim#L269
     * https://github.com/liquidz/vim-iced/blob/2.2.0/ftplugin/clojure.vim#L395
1. Update documents
   * https://github.com/liquidz/vim-iced/blob/2.2.0/doc/vim-iced.txt
   * https://github.com/liquidz/vim-iced/tree/2.2.0/doc/pages/refactoring

As I wrote in the beginning, it may be a bit difficult to implement for the first contribution.
So if you have any questions,  feel free to ask!

**Comment by nbardiuk** [comment]
Thank you for such detailed directions! It would take me forever to figure out these details
